// <auto-generated />
using BCP.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BCP.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230223040920_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BCP.Core.Entities.user.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("BCP.Core.Entities.user.User", b =>
                {
                    b.OwnsOne("BCP.Core.Entities.user.UserDocument", "Document", b1 =>
                        {
                            b1.Property<int>("UserId1")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Citizenship")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("document_citizenship");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("document_id");

                            b1.Property<string>("License")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("document_license");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("document_user_id");

                            b1.HasKey("UserId1");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId1")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.Navigation("Document")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
